### ISSUE TITLE
Fields won't be filtered properly in deep nested objects

### ISSUE THREAD

**Issue by whotwagner** [binkhq/dictfilter#5]
Hello,

dictfilter does not return all matches of deep nested objects. Let's say we have the following object:

```
  bsg = {
       'class': 'Battlestar',
       'model': 'Jupiter',
       'name': 'Galactica',
       'crew': {
           'commander': 'William Adama',
           'xo': 'Saul Tigh',
           'cag': 'Kara Thrace',
           'mook': {
                 'duck': 'quack',
                 'foo': 'bar'
               }
       }
   }
```

If we want to display: "mook.duck" AND "mook.foo" only the one match will show up:

```
result = query(bsg, ['class', 'name', 'crew.commander', 'crew.xo','crew.mook.duck', 'crew.mook.foo'])
# {'class': 'Battlestar', 'name': 'Galactica', 'crew': {'commander': 'William Adama', 'xo': 'Saul Tigh', 'mook': {'foo': 'bar'}}}
```

mook.duck is not in the result.

**Comment by backwardspy** [comment]
thanks for reporting this, i'll have a look at fixing it later on today.

**Comment by backwardspy** [comment]
i've opened #9 to resolve this issue.

new result with your example structure on the fix branch:

```python
>>> query(bsg, ['class', 'name', 'crew.commander', 'crew.xo','crew.mook.duck', 'crew.mook.foo'])
{'class': 'Battlestar', 'name': 'Galactica', 'crew': {'commander': 'William Adama', 'xo': 'Saul Tigh', 'mook': {'duck': 'quack', 'foo': 'bar'}}}
```

**Comment by backwardspy** [comment]
@whotwagner dictfilter 2.0.2 is now available. let me know if this solves the issue for you!

on an unrelated note, i noticed in your fork that you wanted to use a different delimiter. that seems like a useful feature, so i will add it as an option in the next version.

**Comment by whotwagner** [comment]
Oh yeah, please add this feature. It would be very nice. And thank you very much for fixing this issue so quickly
